g++ ProtocoleCapteurs.cpp serialib.cpp C_Capteur.cpp Adresse.cpp TClimat.cpp Capteur.cpp testUnitaireCapteurs.cpp -std=c++0x -pthread -o testUnitaireCapteur
#g++ ProtocoleCapteurs.cpp serialib.cpp C_Capteur.cpp Adresse.cpp TClimat.cpp Capteur.cpp testIntegrationCapteurs.cpp -std=c++0x -pthread -o testIntegrationCapteur
#g++ Climat.cpp C_BDD.cpp testIntegrationClimat.cpp -std=c++0x -o testIntegrationClimat
#g++ ProtocoleCapteurs.cpp serialib.cpp C_Capteur.cpp Adresse.cpp TClimat.cpp Capteur.cpp Climat.cpp C_BDD.cpp testIntegrationCapteurClimat.cpp -std=c++0x -pthread -o testIntegrationCapteurClimat
#g++ Climat.cpp C_BDD.cpp -std=c++0x testUnitaireClimat.cpp -o testUnitaireClimat
#./testIntegrationCapteurClimat
#./testIntegrationClimat
#./testUnitaireClimat
./testUnitaireCapteur
